name: Javascript testing

on:
  - push
  - pull_request

jobs:
  test:
    name: Run unit tests using Vitest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Export node version
        id: node_version
        run: echo ::set-output name=NODE_VERSION::$(cat .nvmrc)
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version-file: '.nvmrc'
      - name: Node Information
        run: node --version
      - name: Install dependencides
        run: >-
          npm ci --legacy-peer-deps
      - name: Run unit tests
        run: >-
          npm run test:unit
  cypress:
    name: Run Cypress tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Export node version
        id: node_version
        run: echo ::set-output name=NODE_VERSION::$(cat .nvmrc)
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version-file: '.nvmrc'
      - name: Node Information
        run: node --version
      - name: Install dependencides
        run: >-
          npm ci  --legacy-peer-deps
      - name: Cypress run
        uses: cypress-io/github-action@v5
        with:
          start: npm start
          wait-on: http://localhost:5173/
          spec: 'tests/e2e/**/*'
          config-file: cypress.config.cjs
          config: video=false
          install: false
          timeout-minutes: 5
          browser: chrome
      # after the test run completes
      # store any screenshots
      # NOTE: screenshots will be generated only if E2E test failed
      # thus we store screenshots only on failures
      # Alternative: create and commit an empty cypress/screenshots folder
      # to always have something to upload
      - uses: actions/upload-artifact@v1
        if: failure()
        with:
          name: cypress-screenshots
          path: tests/e2e/screenshots
