# Triggers on *manual* release creation only. Automated releases
# handle asset creation in release.yml.
# Github actions do not allow chaining actions triggered via the default
# secrets.GITHUB_TOKEN and instead would require the addition of a personal
# authentication token. See:
# https://docs.github.com/en/actions/reference/events-that-trigger-workflows#triggering-new-workflows-using-a-personal-access-token
# While we could go this route, it would require the addition of:
# 1) An automated 'bot' account to handle releases from the sanger/qunathub repo
# 2) Users to add the appropriate token to their forks if they want release behaviour.
# Instead I've opted to maintain separate automated and manual release actions.
# The two actions should remain in sync
# Note that upload_url will differ between the two actions.
name: Build Manual Release

on:
  release:
    types: published

jobs:
  release:
    name: Build Release
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup node
      uses: actions/setup-node@v2
      with:
        node-version: '14'
    - name: Install
      run: yarn install
    - name: Compile build
      run: ./compile-build.sh release.tar.gz dist
    - name: Upload release.gz
      id: upload-release-gz
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }} # Pull the URL from the release step
        asset_path: ./release.tar.gz
        asset_name: release.tar.gz
        asset_content_type: application/gzip
